# -*- coding: utf-8 -*-
"""Movie rating dash bord .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LXgqlLYjD_Mqz5mm4rI35mdLXyXJ_2Q1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set Seaborn style
sns.set(style="whitegrid")

# Load CSV file
file_path = "/content/movies.csv"
df = pd.read_csv(file_path)

# Show first few rows
print("Sample of the dataset:")
print(df.head())

# Check for missing values in required columns
# The columns in the dataframe are 'movieId', 'title', and 'genres'
required_columns = ['title', 'genres'] # Corrected column names
for col in required_columns:
    if col not in df.columns:
        raise ValueError(f"Column '{col}' is missing in your CSV.")

# No 'Rating' column in this dataset, so dropping rows based on it is not applicable.
# df = df.dropna(subset=['Title', 'Rating']) # Removed

# Clean and split genres
df['genres'] = df['genres'].fillna('') # Corrected column name
df_expanded = df.copy()
df_expanded['genres'] = df_expanded['genres'].str.split('|') # Corrected column name
df_expanded = df_expanded.explode('genres') # Corrected column name
df_expanded = df_expanded[df_expanded['genres'] != '']  # remove empty genres

# -----------------------------
# 1. Table: Movie Name and Genres
# -----------------------------
print("\n--- Table: Movie Name and Genres ---")
# No 'Rating' column, showing 'title' and 'genres' instead
print(df[['title', 'genres']].head(10)) # Corrected column names

# -----------------------------
# 2. Bar Chart: Movie Count per Genre
# -----------------------------
# No 'Rating' column for average rating, calculating movie count per genre
genre_counts = df_expanded['genres'].value_counts() # Corrected column name

plt.figure(figsize=(10, 6))
sns.barplot(x=genre_counts.values, y=genre_counts.index, palette='coolwarm')
plt.title('Movie Count per Genre')
plt.xlabel('Movie Count')
plt.ylabel('Genre')
plt.tight_layout()
plt.show()

# -----------------------------
# 3. Pie Chart: Movie Count by Genre
# -----------------------------
# Already calculated genre_counts above
plt.figure(figsize=(8, 8))
plt.pie(genre_counts.values, labels=genre_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Movie Count by Genre')
plt.axis('equal')
plt.tight_layout()
plt.show()

# -----------------------------
# 4. Top Movies (based on available data - no rating)
# -----------------------------
# No 'Rating' column for sorting, just showing the first 5 movies as an example
print("\n--- First 5 Movies in the Dataset ---")
print(df[['title', 'genres']].head(5)) # Corrected column names and removed Rating